### ISSUE TITLE
ERROR:No `generate_interactive_bom.py` command found.

### ISSUE THREAD

**Issue by hoijui** [INTI-CMNB/InteractiveHtmlBom#3]
I first tried many combinations of putting the *InteractiveHtmlBom* dir into the each of the two KiCad plugin dirs suggested in the install instructions (Linux):

* `~/.kicad/scripting/plugins`
* `~/.kicad_plugins`

But the plugin was never found.

I then checked this, as suggested in the install instructions:

```python
import pcbnew
print(pcbnew.PLUGIN_DIRECTORIES_SEARCH)
```
And it resulted in an empty output.

I saw this mentioned here:
https://forum.kicad.info/t/no-plugin-search-directory/16147/6

> ... when python is run separately `pcbnew.PLUGIN_DIRECTORIES_SEARCH` is not initialized.
> It is initialized when run from pcbnew scripting console.

I guess this practically counts as a regression in KiCad from "our" point of view, no?

```
Application: KiCad
Version: 5.1.6+dfsg1-1, release build
Libraries:
    wxWidgets 3.0.5
    libcurl/7.68.0 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.8.0 nghttp2/1.41.0 librtmp/2.3
Platform: Linux 4.19.0-5-amd64 x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
    Boost: 1.67.0
    OpenCASCADE Technology: 7.4.0
    Curl: 7.68.0
    Compiler: GCC 9.3.0 with C++ ABI 1013

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=OFF
    KICAD_USE_OCC=ON
    KICAD_SPICE=ON
```

**Comment by set-soft** [comment]
Hi @hoijui ! 
I was waiting for more info about the IBoM issue.

This fork is focused on the Debian package. @qu1ck is an excellent maintainer, very attentive to IBoM. So this fork has almost the same as the upstream.
The main way to install it is using the Debian package.
I never tried using the "pythonic" way. Or better: I use the pythonic way only to install it in a fake directory used to create the Debian package.

Now that this is clarified lets try to solve the problem. The system level KiCad plugins directory is:
`/usr/share/kicad/scripting/plugins`

And the user directory should be: `~/.config/kicad/scripting/plugins/`
Note that `KICAD_CONFIG_HOME` and `XDG_CONFIG_HOME` can affect that. (`$KICAD_CONFIG_HOME` and `$XDG_CONFIG_HOME\kicad`)

I forgot to add a `/` and the Debian package is installing the plugin in:
`/usr/share/kicad/scripting/pluginsInteractiveHtmlBom`

This should be: `/usr/share/kicad/scripting/plugins/InteractiveHtmlBom` 
But it works because the whole `scripting` dir is scanned by KiCad.

I don't remmember how exactly is supposed to be installed. What I install there are `settings_dialog.fbp` and `__init__.py` from the root of the repo. All the rest of the code is installed at system level like any other Python lib. I think copying the `InteractiveHtmlBom` there will work perfectly. 

Now about the `generate_interactive_bom.py`: I install it in `/usr/bin/`.

The `setup.py` has all this information, but is designed to installs things at system level. Running it (i.e. `pip install .`) should install the plugin in `~/.local/share/kicad/scripting/pluginsInteractiveHtmlBom`. But from what I know KiCad won't find it.

I think KiCad should be looking for plugins there because this is the equivalent to the system level place. But it isn't doing it. Instead is looking for plugins in the config directory, which sounds logic, but isn't simetric.

Did you try installing the .deb?

**Comment by set-soft** [comment]
Some notes: The above mentioned local path seems to work with KiCad 5.99.

For KiCad 5.1.6 `~/.kicad/scripting/plugins` seems to be ok.

And from a @qu1ck post in the forums mentioning important plugins I see none has a `setup.py`.

**Comment by hoijui** [comment]
These are the install instructions:
https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Installation

They state to copy (or symlink) the local repo folder to a plugin directory, and that's it. nothing about installing through a package, neither with `apt` nor with `pip`.
Am I missing something?
None of all these seems to be searched for plugins:

* `~/.kicad/scripting/plugins`
* `~/.kicad_plugins`
* `~/.local/share/kicad/scripting/plugins`
* `/usr/share/kicad/scripting/plugins/`

and this still gives an empty output:

```
$ export KICAD_CONFIG_HOME=$HOME/.config/kicad
$ python3
Python 3.8.5 (default, Jul 20 2020, 18:32:44)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pcbnew
>>> print(pcbnew.PLUGIN_DIRECTORIES_SEARCH)

>>>
```

**Comment by hoijui** [comment]
sorry for the long delay.. I am still thinking about this/your tool almost every day, and I want it to prosper!
I am having a hard time, personally, that's why.

I still did some experimenting, and had some thoughts in general about KiBot.

**Comment by qu1ck** [comment]
@hoijui you should print `pcbnew.PLUGIN_DIRECTORIES_SEARCH` from pcbnew scripting console, not from a python interpreter session started separately.

**Comment by hoijui** [comment]
@qu1ck but I need the plugin be found from python outside pcbnew, not from within, as I want to run fully automated generation from a CI script. I think it is possible, as ... I think kibot and kiplot have done it already.. right, @set-soft ?

**Comment by qu1ck** [comment]
Yes, it's possible but then it's not a plugin, it's just a script and it doesn't matter where you put it.

Read plugin wiki https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Usage#standalone-script

**Comment by hoijui** [comment]
AHAAA....
doh! :D 
thanks a lot @qu1ck !
that is so simple and obvious that until now you did not think of explaining that, and I really.. could not see it. :D 
thanks a lot for the patience!

**Comment by set-soft** [comment]
The 2.3.4 release will include @clayton13 patch (openscopeproject/InteractiveHtmlBom#212)
